# Generated by Django 3.0 on 2020-12-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impfle',
            name='im',
            field=models.ImageField(default='images/avatar.png', null=True, upload_to='Profile/'),
        ),
    ]
