# Generated by Django 3.1 on 2020-12-12 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsApp', '0003_auto_20201211_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impfle',
            name='im',
            field=models.ImageField(default='logo.jpg', null=True, upload_to='UsApp/Profile/'),
        ),
    ]
