# Generated by Django 3.0 on 2020-12-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsApp', '0002_auto_20201211_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impfle',
            name='im',
            field=models.ImageField(default='brand.jpg', null=True, upload_to='Profile/'),
        ),
    ]
