# Generated by Django 3.0 on 2020-12-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsApp', '0003_auto_20201211_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impfle',
            name='im',
            field=models.ImageField(default='avatar.png', null=True, upload_to='Profile/'),
        ),
    ]
